// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "Vision.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



void
PointCloud::operator>>= (cdrStream &_n) const
{
  id >>= _n;
  
#ifndef OMNI_MIXED_ENDIAN_DOUBLE
  if (! _n.marshal_byte_swap()) {
    _n.put_octet_array((_CORBA_Octet*)(T),128,omni::ALIGN_8);
  }
  else 
#endif
  {
    _n.declareArrayLength(omni::ALIGN_8, 128);
    for (_CORBA_ULong _0i0 = 0; _0i0 < 4; _0i0++){
      for (_CORBA_ULong _0i1 = 0; _0i1 < 4; _0i1++){
        T[_0i0][_0i1] >>= _n;
      }
    }
  }
  (const _CORBA_Unbounded_Sequence_Array_w_FixSizeElement< Img::Vec3, Img::Vec3_slice, ::CORBA::Double, 3, 8, 8 > &) point >>= _n;
  (const _CORBA_Unbounded_Sequence_Array_w_FixSizeElement< Img::Vec3, Img::Vec3_slice, ::CORBA::Double, 3, 8, 8 > &) color >>= _n;

}

void
PointCloud::operator<<= (cdrStream &_n)
{
  (::CORBA::Long&)id <<= _n;
  _n.unmarshalArrayDouble((_CORBA_Double*)(T), 16);
  (_CORBA_Unbounded_Sequence_Array_w_FixSizeElement< Img::Vec3, Img::Vec3_slice, ::CORBA::Double, 3, 8, 8 > &)point <<= _n;
  (_CORBA_Unbounded_Sequence_Array_w_FixSizeElement< Img::Vec3, Img::Vec3_slice, ::CORBA::Double, 3, 8, 8 > &)color <<= _n;

}

void
TimedPointCloud::operator>>= (cdrStream &_n) const
{
  (const RTC::Time&) tm >>= _n;
  (const PointCloud&) data >>= _n;
  error_code >>= _n;

}

void
TimedPointCloud::operator<<= (cdrStream &_n)
{
  (RTC::Time&)tm <<= _n;
  (PointCloud&)data <<= _n;
  (::CORBA::Long&)error_code <<= _n;

}

void
Stereo3D::operator>>= (cdrStream &_n) const
{
  (const TimedPointCloud&) obj >>= _n;
  (const Img::TimedMultiCameraImage&) mimg >>= _n;

}

void
Stereo3D::operator<<= (cdrStream &_n)
{
  (TimedPointCloud&)obj <<= _n;
  (Img::TimedMultiCameraImage&)mimg <<= _n;

}

void
TimedStereo3D::operator>>= (cdrStream &_n) const
{
  (const RTC::Time&) tm >>= _n;
  (const Stereo3D&) data >>= _n;
  error_code >>= _n;

}

void
TimedStereo3D::operator<<= (cdrStream &_n)
{
  (RTC::Time&)tm <<= _n;
  (Stereo3D&)data <<= _n;
  (::CORBA::Long&)error_code <<= _n;

}

Reconstruct3DService_ptr Reconstruct3DService_Helper::_nil() {
  return ::Reconstruct3DService::_nil();
}

::CORBA::Boolean Reconstruct3DService_Helper::is_nil(::Reconstruct3DService_ptr p) {
  return ::CORBA::is_nil(p);

}

void Reconstruct3DService_Helper::release(::Reconstruct3DService_ptr p) {
  ::CORBA::release(p);
}

void Reconstruct3DService_Helper::marshalObjRef(::Reconstruct3DService_ptr obj, cdrStream& s) {
  ::Reconstruct3DService::_marshalObjRef(obj, s);
}

Reconstruct3DService_ptr Reconstruct3DService_Helper::unmarshalObjRef(cdrStream& s) {
  return ::Reconstruct3DService::_unmarshalObjRef(s);
}

void Reconstruct3DService_Helper::duplicate(::Reconstruct3DService_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

Reconstruct3DService_ptr
Reconstruct3DService::_duplicate(::Reconstruct3DService_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

Reconstruct3DService_ptr
Reconstruct3DService::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


Reconstruct3DService_ptr
Reconstruct3DService::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

Reconstruct3DService_ptr
Reconstruct3DService::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_Reconstruct3DService _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_Reconstruct3DService* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_Reconstruct3DService;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* Reconstruct3DService::_PD_repoId = "IDL:Reconstruct3DService:1.0";


_objref_Reconstruct3DService::~_objref_Reconstruct3DService() {
  
}


_objref_Reconstruct3DService::_objref_Reconstruct3DService(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::Reconstruct3DService::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
_objref_Reconstruct3DService::_ptrToObjRef(const char* id)
{
  if( id == ::Reconstruct3DService::_PD_repoId )
    return (::Reconstruct3DService_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::Reconstruct3DService::_PD_repoId) )
    return (::Reconstruct3DService_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _wvoid
class _0RL_cd_58d1097e1d9f3b97_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_58d1097e1d9f3b97_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 1, 0, 0, upcall)
  {
    
  }
  
  
    
  
  
};

// Local call call-back function.
static void
_0RL_lcfn_58d1097e1d9f3b97_10000000(omniCallDescriptor*, omniServant* svnt)
{
  
  _impl_Reconstruct3DService* impl = (_impl_Reconstruct3DService*) svnt->_ptrToInterface(Reconstruct3DService::_PD_repoId);
  impl->reconstruct();


}

void _objref_Reconstruct3DService::reconstruct()
{
  _0RL_cd_58d1097e1d9f3b97_00000000 _call_desc(_0RL_lcfn_58d1097e1d9f3b97_10000000, "reconstruct", 12);


  _invoke(_call_desc);



}
_pof_Reconstruct3DService::~_pof_Reconstruct3DService() {}


omniObjRef*
_pof_Reconstruct3DService::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_Reconstruct3DService(ior, id);
}


::CORBA::Boolean
_pof_Reconstruct3DService::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::Reconstruct3DService::_PD_repoId) )
    return 1;
  
  return 0;
}

const _pof_Reconstruct3DService _the_pof_Reconstruct3DService;

_impl_Reconstruct3DService::~_impl_Reconstruct3DService() {}


::CORBA::Boolean
_impl_Reconstruct3DService::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "reconstruct") ) {

    _0RL_cd_58d1097e1d9f3b97_00000000 _call_desc(_0RL_lcfn_58d1097e1d9f3b97_10000000, "reconstruct", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
_impl_Reconstruct3DService::_ptrToInterface(const char* id)
{
  if( id == ::Reconstruct3DService::_PD_repoId )
    return (::_impl_Reconstruct3DService*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::Reconstruct3DService::_PD_repoId) )
    return (::_impl_Reconstruct3DService*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
_impl_Reconstruct3DService::_mostDerivedRepoId()
{
  return ::Reconstruct3DService::_PD_repoId;
}

RecognitionService_ptr RecognitionService_Helper::_nil() {
  return ::RecognitionService::_nil();
}

::CORBA::Boolean RecognitionService_Helper::is_nil(::RecognitionService_ptr p) {
  return ::CORBA::is_nil(p);

}

void RecognitionService_Helper::release(::RecognitionService_ptr p) {
  ::CORBA::release(p);
}

void RecognitionService_Helper::marshalObjRef(::RecognitionService_ptr obj, cdrStream& s) {
  ::RecognitionService::_marshalObjRef(obj, s);
}

RecognitionService_ptr RecognitionService_Helper::unmarshalObjRef(cdrStream& s) {
  return ::RecognitionService::_unmarshalObjRef(s);
}

void RecognitionService_Helper::duplicate(::RecognitionService_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

RecognitionService_ptr
RecognitionService::_duplicate(::RecognitionService_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

RecognitionService_ptr
RecognitionService::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


RecognitionService_ptr
RecognitionService::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

RecognitionService_ptr
RecognitionService::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_RecognitionService _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_RecognitionService* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_RecognitionService;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* RecognitionService::_PD_repoId = "IDL:RecognitionService:1.0";


_objref_RecognitionService::~_objref_RecognitionService() {
  
}


_objref_RecognitionService::_objref_RecognitionService(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::RecognitionService::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
_objref_RecognitionService::_ptrToObjRef(const char* id)
{
  if( id == ::RecognitionService::_PD_repoId )
    return (::RecognitionService_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::RecognitionService::_PD_repoId) )
    return (::RecognitionService_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _clong
class _0RL_cd_58d1097e1d9f3b97_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_58d1097e1d9f3b97_20000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  ::CORBA::Long result;
};

void _0RL_cd_58d1097e1d9f3b97_20000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_58d1097e1d9f3b97_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Long&)result <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_58d1097e1d9f3b97_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_58d1097e1d9f3b97_20000000* tcd = (_0RL_cd_58d1097e1d9f3b97_20000000*)cd;
  _impl_RecognitionService* impl = (_impl_RecognitionService*) svnt->_ptrToInterface(RecognitionService::_PD_repoId);
  tcd->result = impl->getModelID();


}

::CORBA::Long _objref_RecognitionService::getModelID()
{
  _0RL_cd_58d1097e1d9f3b97_20000000 _call_desc(_0RL_lcfn_58d1097e1d9f3b97_30000000, "getModelID", 11);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  void_i_clong
class _0RL_cd_58d1097e1d9f3b97_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_58d1097e1d9f3b97_40000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  ::CORBA::Long arg_0;
};

void _0RL_cd_58d1097e1d9f3b97_40000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_58d1097e1d9f3b97_40000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_58d1097e1d9f3b97_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_58d1097e1d9f3b97_40000000* tcd = (_0RL_cd_58d1097e1d9f3b97_40000000*)cd;
  _impl_RecognitionService* impl = (_impl_RecognitionService*) svnt->_ptrToInterface(RecognitionService::_PD_repoId);
  impl->setModelID(tcd->arg_0);


}

void _objref_RecognitionService::setModelID(::CORBA::Long ModelID)
{
  _0RL_cd_58d1097e1d9f3b97_40000000 _call_desc(_0RL_lcfn_58d1097e1d9f3b97_50000000, "setModelID", 11);
  _call_desc.arg_0 = ModelID;

  _invoke(_call_desc);



}
_pof_RecognitionService::~_pof_RecognitionService() {}


omniObjRef*
_pof_RecognitionService::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_RecognitionService(ior, id);
}


::CORBA::Boolean
_pof_RecognitionService::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::RecognitionService::_PD_repoId) )
    return 1;
  
  return 0;
}

const _pof_RecognitionService _the_pof_RecognitionService;

_impl_RecognitionService::~_impl_RecognitionService() {}


::CORBA::Boolean
_impl_RecognitionService::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "getModelID") ) {

    _0RL_cd_58d1097e1d9f3b97_20000000 _call_desc(_0RL_lcfn_58d1097e1d9f3b97_30000000, "getModelID", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setModelID") ) {

    _0RL_cd_58d1097e1d9f3b97_40000000 _call_desc(_0RL_lcfn_58d1097e1d9f3b97_50000000, "setModelID", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
_impl_RecognitionService::_ptrToInterface(const char* id)
{
  if( id == ::RecognitionService::_PD_repoId )
    return (::_impl_RecognitionService*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::RecognitionService::_PD_repoId) )
    return (::_impl_RecognitionService*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
_impl_RecognitionService::_mostDerivedRepoId()
{
  return ::RecognitionService::_PD_repoId;
}

RecognitionResultViewerService_ptr RecognitionResultViewerService_Helper::_nil() {
  return ::RecognitionResultViewerService::_nil();
}

::CORBA::Boolean RecognitionResultViewerService_Helper::is_nil(::RecognitionResultViewerService_ptr p) {
  return ::CORBA::is_nil(p);

}

void RecognitionResultViewerService_Helper::release(::RecognitionResultViewerService_ptr p) {
  ::CORBA::release(p);
}

void RecognitionResultViewerService_Helper::marshalObjRef(::RecognitionResultViewerService_ptr obj, cdrStream& s) {
  ::RecognitionResultViewerService::_marshalObjRef(obj, s);
}

RecognitionResultViewerService_ptr RecognitionResultViewerService_Helper::unmarshalObjRef(cdrStream& s) {
  return ::RecognitionResultViewerService::_unmarshalObjRef(s);
}

void RecognitionResultViewerService_Helper::duplicate(::RecognitionResultViewerService_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

RecognitionResultViewerService_ptr
RecognitionResultViewerService::_duplicate(::RecognitionResultViewerService_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

RecognitionResultViewerService_ptr
RecognitionResultViewerService::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


RecognitionResultViewerService_ptr
RecognitionResultViewerService::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

RecognitionResultViewerService_ptr
RecognitionResultViewerService::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_RecognitionResultViewerService _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_RecognitionResultViewerService* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_RecognitionResultViewerService;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* RecognitionResultViewerService::_PD_repoId = "IDL:RecognitionResultViewerService:1.0";


_objref_RecognitionResultViewerService::~_objref_RecognitionResultViewerService() {
  
}


_objref_RecognitionResultViewerService::_objref_RecognitionResultViewerService(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::RecognitionResultViewerService::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
_objref_RecognitionResultViewerService::_ptrToObjRef(const char* id)
{
  if( id == ::RecognitionResultViewerService::_PD_repoId )
    return (::RecognitionResultViewerService_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::RecognitionResultViewerService::_PD_repoId) )
    return (::RecognitionResultViewerService_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _wvoid_i_cImg_mTimedMultiCameraImage_i_cRTC_mTimedDoubleSeq
class _0RL_cd_58d1097e1d9f3b97_60000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_58d1097e1d9f3b97_60000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 1, 0, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  Img::TimedMultiCameraImage_var arg_0_;
  const Img::TimedMultiCameraImage* arg_0;
  TimedRecognitionResult_var arg_1_;
  const TimedRecognitionResult* arg_1;
};

void _0RL_cd_58d1097e1d9f3b97_60000000::marshalArguments(cdrStream& _n)
{
  (const Img::TimedMultiCameraImage&) *arg_0 >>= _n;
  (const TimedRecognitionResult&) *arg_1 >>= _n;

}

void _0RL_cd_58d1097e1d9f3b97_60000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new Img::TimedMultiCameraImage;
  (Img::TimedMultiCameraImage&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();
  arg_1_ = new TimedRecognitionResult;
  (TimedRecognitionResult&)arg_1_ <<= _n;
  arg_1 = &arg_1_.in();

}

// Local call call-back function.
static void
_0RL_lcfn_58d1097e1d9f3b97_70000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_58d1097e1d9f3b97_60000000* tcd = (_0RL_cd_58d1097e1d9f3b97_60000000*)cd;
  _impl_RecognitionResultViewerService* impl = (_impl_RecognitionResultViewerService*) svnt->_ptrToInterface(RecognitionResultViewerService::_PD_repoId);
  impl->display(*tcd->arg_0, *tcd->arg_1);


}

void _objref_RecognitionResultViewerService::display(const Img::TimedMultiCameraImage& frame, const TimedRecognitionResult& pos)
{
  _0RL_cd_58d1097e1d9f3b97_60000000 _call_desc(_0RL_lcfn_58d1097e1d9f3b97_70000000, "display", 8);
  _call_desc.arg_0 = &(Img::TimedMultiCameraImage&) frame;
  _call_desc.arg_1 = &(TimedRecognitionResult&) pos;

  _invoke(_call_desc);



}
_pof_RecognitionResultViewerService::~_pof_RecognitionResultViewerService() {}


omniObjRef*
_pof_RecognitionResultViewerService::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_RecognitionResultViewerService(ior, id);
}


::CORBA::Boolean
_pof_RecognitionResultViewerService::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::RecognitionResultViewerService::_PD_repoId) )
    return 1;
  
  return 0;
}

const _pof_RecognitionResultViewerService _the_pof_RecognitionResultViewerService;

_impl_RecognitionResultViewerService::~_impl_RecognitionResultViewerService() {}


::CORBA::Boolean
_impl_RecognitionResultViewerService::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "display") ) {

    _0RL_cd_58d1097e1d9f3b97_60000000 _call_desc(_0RL_lcfn_58d1097e1d9f3b97_70000000, "display", 8, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
_impl_RecognitionResultViewerService::_ptrToInterface(const char* id)
{
  if( id == ::RecognitionResultViewerService::_PD_repoId )
    return (::_impl_RecognitionResultViewerService*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::RecognitionResultViewerService::_PD_repoId) )
    return (::_impl_RecognitionResultViewerService*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
_impl_RecognitionResultViewerService::_mostDerivedRepoId()
{
  return ::RecognitionResultViewerService::_PD_repoId;
}

POA_Reconstruct3DService::~POA_Reconstruct3DService() {}

POA_RecognitionService::~POA_RecognitionService() {}

POA_RecognitionResultViewerService::~POA_RecognitionResultViewerService() {}

